### ISSUE TITLE
Nice, but can't run

### ISSUE THREAD

**Issue by wenkesj** [patrickhahn/2048#1]
Looks good, I just can't run the 2048

@austinkelleher

**Comment by austinkelleher** [comment]
Yes, I'm experiencing this same issue. I run `./README.md` and there is no 2048. Pls fix.

**Comment by wenkesj** [comment]
@patrickhahn a little confused, I tried to run it:

```sh
$ ./README.md
permission denied: ./README.md
```

Here's my OS info, pls fix
```
Apple LLVM version 9.0.0
Target: x86_64-apple-darwin16.7.0
Thread model: posix
```

I need this,

Goteem

**Comment by patrickhahn** [comment]
Thank you both for bringing this important issue to our attention. The bug has since been fixed and README.md has been updated with instructions to run the game. We hope your needs have been addressed to your satisfaction. 

Patrick & the Haskell 2048 team

**Comment by wenkesj** [comment]
I just died, and went to 2048 heaven, thank you for your attention and kind words.
